version: '3.6'

networks:
  gitlab-network:
    name: gitlab-network
    driver: bridge

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    networks:
      - gitlab-network
    environment:
      GITLAB_ROOT_PASSWORD: "5iveL!fe"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        nginx['listen_port'] = 80
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        registry_external_url 'http://gitlab:5001'
        registry['enable'] = true
        registry_nginx['listen_port'] = 5001
    ports:
      - '8080:80'
      - '8443:443'
      - '2222:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    shm_size: '256m'

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    networks:
      - gitlab-network
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - 'gitlab_runner_config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
  volumes:
  gitlab_config:
  gitlab_data:
  gitlab_logs:
  gitlab_runner_config: